# -*- coding: utf-8 -*-
"""analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KF-6FMGIW3LiZM8HoVy9_uE15qIM6QJg
"""

import pandas as pd
import numpy as np

class DataAnalyzer:
    def __init__(self, df: pd.DataFrame):
        self.df = df

    def get_analysis(self):
        """Main function to generate all EDA data"""
        return {
            "correlations": self.get_correlations(),
            "column_stats": self.get_column_types(),
            "geo_data": self.get_geo_details(),
            "chart_data": self.get_chart_data()
        }

    def get_correlations(self):
        """Calculates correlation between numeric columns for a heatmap"""
        numeric_df = self.df.select_dtypes(include=[np.number])
        if numeric_df.empty:
            return {}
        # We limit to top 10 columns if there are too many, to avoid a messy chart
        corr = numeric_df.corr().round(2)
        return corr.to_dict()

    def get_column_types(self):
        """Identifies which columns are numeric vs categorical"""
        stats = []
        for col in self.df.columns:
            stats.append({
                "name": col,
                "type": str(self.df[col].dtype),
                "unique_values": self.df[col].nunique()
            })
        return stats

    def get_geo_details(self):
        """Detects if data has lat/long for maps"""
        cols = [c.lower() for c in self.df.columns]
        has_lat = any(x in cols for x in ['lat', 'latitude'])
        has_lon = any(x in cols for x in ['lon', 'longitude', 'lng'])

        if has_lat and has_lon:
            # Return top 100 points for the map to avoid lag
            geo_df = self.df.dropna(subset=[
                [c for c in self.df.columns if c.lower() in ['lat', 'latitude']][0],
                [c for c in self.df.columns if c.lower() in ['lon', 'longitude', 'lng']][0]
            ])
            return geo_df.head(100).to_dict(orient='records')
        return None

    def get_chart_data(self):
        """Prepares data for bar charts (Top 10 values for categorical columns)"""
        charts = {}
        cat_cols = self.df.select_dtypes(include=['object']).columns[:3] # Limit to first 3
        for col in cat_cols:
            charts[col] = self.df[col].value_counts().head(10).to_dict()
        return charts