# -*- coding: utf-8 -*-
"""janitor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXyk2i3E801ZDzHfZvtqE1dmfz_1i4JG
"""

import pandas as pd
import numpy as np

class DataJanitor:
    def __init__(self, df: pd.DataFrame):
        self.df = df

    def clean(self):
        self.remove_duplicates()
        self.fix_dates()
        self.handle_missing_values()
        self.split_merged_columns()
        return self.df

    def remove_duplicates(self):
        self.df.drop_duplicates(inplace=True)

    def fix_dates(self):
        for col in self.df.columns:
            if 'date' in col.lower() or 'time' in col.lower():
                self.df[col] = pd.to_datetime(self.df[col], errors='coerce')

    def handle_missing_values(self):
        for col in self.df.columns:
            if self.df[col].isnull().sum() > 0:
                if self.df[col].dtype in [np.float64, np.int64]:
                    self.df[col] = self.df[col].fillna(self.df[col].median())
                else:
                    self.df[col] = self.df[col].fillna("Unknown")

    def split_merged_columns(self):
        for col in self.df.select_dtypes(include=['object']).columns:
            sample = self.df[col].dropna().head(5).astype(str)
            for sep in [',', '|', ';', ' - ']:
                if sample.str.contains(sep).all():
                    new_cols = self.df[col].str.split(sep, expand=True)
                    if 1 < new_cols.shape[1] <= 3:
                        for i in range(new_cols.shape[1]):
                            self.df[f"{col}_{i+1}"] = new_cols[i].str.strip()
                        self.df.drop(columns=[col], inplace=True)
                        break

    def get_summary(self):
        return {
            "total_rows": len(self.df),
            "total_cols": len(self.df.columns),
            "columns": self.df.columns.tolist(),
            "null_counts": self.df.isnull().sum().to_dict()
        }