# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TODrx-cU-_QDbwMbHnW5hSrCNuxEtLFq
"""

from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd
import io
from janitor import DataJanitor
from analyzer import DataAnalyzer # <-- Import the new analyzer

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/upload")
async def upload_data(file: UploadFile = File(...)):
    extension = file.filename.split(".")[-1].lower()
    contents = await file.read()

    try:
        if extension == "csv":
            df = pd.read_csv(io.BytesIO(contents))
        elif extension in ["xlsx", "xls"]:
            df = pd.read_excel(io.BytesIO(contents))
        else:
            raise HTTPException(status_code=400, detail="Invalid file type")
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Error reading file: {str(e)}")

    # 1. Clean the data (Part 2)
    janitor = DataJanitor(df)
    clean_df = janitor.clean()
    summary = janitor.get_summary()

    # 2. Analyze the data (Part 3)
    analyzer = DataAnalyzer(clean_df)
    analysis_results = analyzer.get_analysis()

    return {
        "message": "Data cleaned and analyzed successfully",
        "summary": summary,
        "analysis": analysis_results, # <-- New Analysis Data!
        "preview": clean_df.head(10).to_dict(orient="records")
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)