# -*- coding: utf-8 -*-
"""ml_engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vD0zk4e6zVor79ClhNAzyBpqgBQzioNJ
"""

def run(self):
        # 1. Drop rows where target is missing
        self.df = self.df.dropna(subset=[self.target])

        # 2. Extract Features from Date Columns (The Fix!)
        # We find any date columns and turn them into numbers
        for col in self.df.select_dtypes(include=['datetime64']).columns:
            self.df[f"{col}_year"] = self.df[col].dt.year
            self.df[f"{col}_month"] = self.df[col].dt.month
            self.df[f"{col}_day"] = self.df[col].dt.day
            self.df[f"{col}_dayofweek"] = self.df[col].dt.dayofweek
            # Now we drop the original date column because the model can't read it
            self.df.drop(columns=[col], inplace=True)

        # 3. Separate Features (X) and Target (y)
        X = self.df.drop(columns=[self.target])
        y = self.df[self.target]

        # 4. Simple Encoding for X (Turn text columns into numbers)
        le = LabelEncoder()
        for col in X.select_dtypes(include=['object']).columns:
            # We convert to string first to handle any mixed types
            X[col] = le.fit_transform(X[col].astype(str))

        # 5. Detect Task Type (Regression vs Classification)
        if y.dtype == 'object' or y.nunique() < 15:
            self.task_type = "classification"
            y = le.fit_transform(y.astype(str))
            self.model = RandomForestClassifier(n_estimators=100, random_state=42)
        else:
            self.task_type = "regression"
            self.model = RandomForestRegressor(n_estimators=100, random_state=42)

        # 6. Split and Train
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        self.model.fit(X_train, y_train)

        # 7. Evaluate
        predictions = self.model.predict(X_test)
        if self.task_type == "classification":
            score = accuracy_score(y_test, predictions)
            metric = "Accuracy"
        else:
            score = r2_score(y_test, predictions)
            metric = "R2 Score"

        # 8. Feature Importance
        importance = dict(zip(X.columns, self.model.feature_importances_.tolist()))
        sorted_importance = dict(sorted(importance.items(), key=lambda item: item[1], reverse=True))

        return {
            "task": self.task_type,
            "metric": metric,
            "score": round(score, 4),
            "feature_importance": sorted_importance
        }