# -*- coding: utf-8 -*-
"""storyteller

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ra1aFoGdJIceQw-JWgtfkZJAGZHj1F_R
"""

import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

# Setup the AI client
client = OpenAI(api_key=os.getenv("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"))

class AIStoryteller:
    def __init__(self):
        pass

    def generate_report(self, analysis_data, ml_results):
        """Combines all data into a professional strategic story"""

        prompt = f"""
        You are a Senior Data Strategy Consultant. Analyze these results and write a report.

        DATASET STATS:
        - Columns: {analysis_data['column_stats']}
        - Top Correlations: {analysis_data['correlations']}

        MACHINE LEARNING RESULTS:
        - Task: {ml_results['task']}
        - Model Performance: {ml_results['score']}
        - Most Important Factors: {ml_results['feature_importance']}

        FORMAT YOUR RESPONSE LIKE THIS:
        1. **Executive Summary**: A high-level view of the data.
        2. **Deep Insights**: What do the correlations and ML results actually mean?
        3. **Strategic Recommendations**: 3 clear business actions the user should take.
        4. **Potential Risks**: What should the user be careful about?

        Tone: Professional, Insightful, and Action-oriented.
        """

        try:
            response = client.chat.completions.create(
                model="gpt-4o-mini", # You can use "llama-3.1-70b-versatile" if using Groq
                messages=[
                    {"role": "system", "content": "You are a data storytelling expert."},
                    {"role": "user", "content": prompt}
                ]
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"The AI is currently analyzing but ran into an error: {str(e)}"